version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: esp13_mysql
        command:  --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root_passwd
            - MYSQL_DATABASE=bus_db
            - MYSQL_USER=esp13
            - MYSQL_PASSWORD=esp13
        ports:
            - '13306:3306'

    zookeeper:
        image: wurstmeister/zookeeper
        container_name: esp13_zookeeper
        ports:
            - "13181:2181"
            
    kafka:
        image: wurstmeister/kafka
        container_name: esp13_kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "topic1"
#        volumes:
#            - /var/run/docker.sock:/var/run/docker.sock
            
            
            
 # Wipe and reset docker container (if needed): 
 #      docker-compose rm -v
 #      Delete /tmp/mysql